### ISSUE TITLE
Add donations album to FB

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cflbajans#139]
A sustainable method maintaining the pics related to donations and scholarship winners may be to place them in a FB album by themselves. @KillahB thoughts?

**Comment by KillahB** [comment]
@kwhitehall That sounds great!

**Comment by KillahB** [comment]
- [ ] Create donations album

**Comment by kwhitehall** [comment]
Done on FB and added to photo albums on website in PR #143
