### ISSUE TITLE
Suggestions for Correction - Index

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cflbajans#2]
Home
- [x] Header: Change CFLBajans to CFL Bajans (two words)
- [x] Mission Statement: add the known acronym 'BAOCF' prior to 'CFL Bajans'
- [x] Mission Statement: 2nd sentence, change or add 'Barbadians' to / with 'Bajans'; add commas after 'Barbados,' 'cultural' and 'operations'

About
- [x] Rearrange the bullets and have 'Join Us' as the last bullet
- [x] Space between CFL and Bajans
- [x] Rename sections from a question to a statement 

Upcoming Events
- [x] Font colours on bullets not rendering correctly on a Windows OS

Contact
- [x] Reword "Please fill out the form below for contact as soon as possible."

Footer
- [x] Add more identifiers, similar to the header, in the footer (BAOCF & Central Florida Bajans)

**Comment by kwhitehall** [comment]
@KillahB are the Font colours on bullets on the upcoming events still not rendering correctly on a Windows OS? If the issue has been addressed, please check off and close this issue.

**Comment by KillahB** [comment]
@kwhitehall I'll download the repo again and verify; please standby.

**Comment by KillahB** [comment]
Looks good @kwhitehall
