### ISSUE TITLE
create all associated emails

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cflbajans#24]
On the server side of things create the emails for individuals and forward accordingly.

**Comment by kwhitehall** [comment]
all address have been created. Currently there is what appears to be a DNS issue thus only emails between the domain are being received. This is being investigated. Will report once this is done.

**Comment by KillahB** [comment]
@kwhitehall Thanks. Keep us posted as we'll have to link the emails to the FB and IG log in.

**Comment by kwhitehall** [comment]
Ack'ed

**Comment by kwhitehall** [comment]
The DNS is solved and the emails are working.
