### ISSUE TITLE
Update 'About' Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cflbajans#52]
- [x] Change Executive Member terms from 2016-2018 to 2016-2017
- [ ] Obtain short bios from Executive Board and update
     - [x] Dale Husbands
     - [x] Rodney Marshall
     - [x] Dennis Morris
     - [x] Karen Johnson
     - [ ] Tyrell Pile
     - [ ] Don Monroe

- [x] In 'Where we are from,' remove ' which is in the Caribbean'
- [x] Chron jobs to automatically run scripts to update

**Comment by kwhitehall** [comment]
Moving cron jobs issue to a separate issue as this is unrelated to content.

**Comment by KillahB** [comment]
@kwhitehall Marked it as complete, due to pending new issue.

**Comment by KillahB** [comment]
PR #68 addressed the verbiage corrections

**Comment by kwhitehall** [comment]
I believe we've got what we are going to get. Closing this issue. If anything, updates can be made when the new ones are added in #105.
