### ISSUE TITLE
Update 'Index' page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cflbajans#53]
- [ ] Chron jobs to automatically run scripts to update
- [x] Instagram link to open in new window
- [x] Facebook link to open in new window

**Comment by kwhitehall** [comment]
Ack'ed @KillahB. The changes for the IG and FB link will have to be done for all pages . I'll update all when addressing this issue.

**Comment by kwhitehall** [comment]
IG and FB links opening in new window addressed in PR #59

**Comment by kwhitehall** [comment]
Moving cron jobs issue to a separate issue as this is unrelated to content. See issue #62
