### ISSUE TITLE
Update Facebook Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cflbajans#56]
- [x] Update 'About' to match and link with the new website

- [x] Update webpage address

- [x] Update Events

- [x] Annotate new website and push on FB 

- [x] Create FB profile with new email address as CFLBajans

**Comment by KillahB** [comment]
- [ ] Push new website on Twitter

**Comment by KillahB** [comment]
- [ ] Push new website on IG

**Comment by kwhitehall** [comment]
All of these tasks are completed, so closing this issue.
