### ISSUE TITLE
set up cron jobs on server for automatic updating

### ISSUE THREAD

**Issue by kwhitehall** [CFLBajans/cflbajans#62]
- pulling from GH hrly

**Comment by kwhitehall** [comment]
- [ ] pull hourly from Github and update website
- [ ] update new meeting date on third Sunday 
To address this, the repo [utils](https://github.com/CFLBajans/utils) have been added to the organization. Note that there are also scripts server side in this implementation. They will be included in the [utils](https://github.com/CFLBajans/utils) with dummy paths, etc.

**Comment by kwhitehall** [comment]
@KillahB @millserd any other tasks to be automated?

**Comment by millserd** [comment]
Can't think of anything at the moment.

**Comment by KillahB** [comment]
@kwhitehall I don't see any... I'll update as I run across any more.

**Comment by kwhitehall** [comment]
Thanks guys.
