### ISSUE TITLE
Suggestions for Correction - 'About' Page

### ISSUE THREAD

**Issue by KillahB** [CFLBajans/cflbajans#8]
Who We Are
- [x] Rename header to 'Who We Are' to match the previous link
- [x] Add the known acronym 'BAOCF' prior to 'CFL Bajans'
- [x] Add commas after: 1991; community; Barbados (3rd)
- [x] Remove Barbados (2nd)
- [x] Consider breaking the 2nd sentence off into 2. Full-stop after 'Barbados' and resume with 'This includes' 
- [x] Add 'Bajan' in brackets after 'Barbadian' (2 areas)

Friends
- [x] Move 'Friends' tab to end of page

What We Do
- [x] Add 'Bajan' after 'Barbadian' in the 'Showcase' bullet

Join Us
- [x] Relocate to after 'Where We Are From'

Where we are from
- [x] Relocate the food tip to after the fun facts

Featured Bajan
- [x] 'Featured Bajan' page to be developed

**Comment by kwhitehall** [comment]
Relocate the food tip to after the fun facts is a rendering issue.
